# Generated by Django 3.0.5 on 2020-05-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
                ('unique_squirrel_id', models.CharField(max_length=20, verbose_name='Squirrel')),
                ('hectare', models.CharField(max_length=3, verbose_name='Hectare')),
                ('shift', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], max_length=2, verbose_name='Shift')),
                ('date', models.DateField(verbose_name='Date')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], max_length=50, verbose_name='Age')),
                ('primary_fur_color', models.CharField(choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black')], max_length=50, verbose_name='Primary Fur Color')),
                ('location', models.CharField(choices=[('ground_plane', 'Ground Plane'), ('above_ground', 'Above Ground')], max_length=50, verbose_name='Location')),
                ('specific_location', models.CharField(max_length=100, verbose_name='Specific Location')),
                ('running', models.BooleanField(verbose_name='Running')),
                ('chasing', models.BooleanField(verbose_name='Chasing')),
                ('climbing', models.BooleanField(verbose_name='Climbing')),
                ('eating', models.BooleanField(verbose_name='Eating')),
                ('foraging', models.BooleanField(verbose_name='Foraging')),
                ('other_activities', models.CharField(max_length=100, verbose_name='Other Activities')),
                ('kuks', models.BooleanField(verbose_name='Kuks')),
                ('quaas', models.BooleanField(verbose_name='Quaas')),
                ('moans', models.BooleanField(verbose_name='Moans')),
                ('tail_flags', models.BooleanField(verbose_name='Tail flags')),
                ('tail_twitches', models.BooleanField(verbose_name='Tail twitches')),
                ('approaches', models.BooleanField(verbose_name='Approaches')),
                ('indifferent', models.BooleanField(verbose_name='Indifferent')),
                ('runs_from', models.BooleanField(verbose_name='Runs from')),
            ],
        ),
    ]
